import { type PnlRecord } from '../repositories/pnlRepo.js';
export declare function getTodayUtcDate(): string;
export declare function diffDaysUtc(startDate: string, endDate: string): number;
export declare function recalcByPnl(startingCapital: number, pnl: number, days: number): {
    endingCapital: number;
    returnRate: number;
    annualizedReturn: number;
};
export declare function formatPnlRecord(record: PnlRecord | undefined): {
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null;
export declare function formatRevenue(record: any): {
    id: any;
    periodLabel: any;
    startDate: any;
    endDate: any;
    initialInvestment: any;
    fairValue: any;
    cashValue: any;
    profit: any;
    returnRate: any;
    runningDays: any;
    annualizedReturn: any;
};
export declare function createWeeklyPnlRecord(input: {
    startDate: string;
    startingCapital?: number;
    endDate?: string;
    pnl?: number;
    days?: number;
}): Promise<{
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null>;
export declare function createMonthlyPnlRecord(input: {
    month: string;
    startingCapital?: number;
    pnl?: number;
    days?: number;
    auto?: boolean;
    endDate?: string;
}): Promise<{
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null>;
export declare function updateRevenueOverview(data: {
    periodLabel: string;
    startDate: string;
    endDate: string;
    initialInvestment: number;
    fairValue: number;
    cashValue: number;
}): {
    id: any;
    periodLabel: any;
    startDate: any;
    endDate: any;
    initialInvestment: any;
    fairValue: any;
    cashValue: any;
    profit: any;
    returnRate: any;
    runningDays: any;
    annualizedReturn: any;
};
export declare function getRevenueOverview(): {
    id: any;
    periodLabel: any;
    startDate: any;
    endDate: any;
    initialInvestment: any;
    fairValue: any;
    cashValue: any;
    profit: any;
    returnRate: any;
    runningDays: any;
    annualizedReturn: any;
} | null;
export declare function updatePnlRecordById(id: string, data: any): {
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null;
export declare function deletePnlRecordById(id: string): boolean;
export declare function runDailyPnlAutoAccumulate(today?: string): Promise<{
    updated: number;
}>;
export declare function getWeeklyPnlRecords(filters: {
    from?: string;
    to?: string;
}): ({
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null)[];
export declare function getMonthlyPnlRecords(filters: {
    from?: string;
    to?: string;
}): ({
    id: string;
    period: "weekly" | "monthly";
    startDate: string;
    endDate: string;
    startingCapital: number;
    endingCapital: number;
    pnl: number;
    returnRate: number;
    days: number;
    annualizedReturn: number;
    isAdjusted: boolean;
    status: import("../repositories/pnlRepo.js").PnlStatus;
    autoAccumulate: boolean;
    editable: boolean;
    incomeUniswap: number;
    incomeMorpho: number;
    incomeHlp: number;
    incomeTotal: number;
    lastAutoUpdateAt: string | null;
    basePnl: number;
    lastUniswapValue: number;
    lastMorphoValue: number;
    lastHlpValue: number;
} | null)[];
